version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/database/
    ports:
      - 5432:5432
